/:
  controller: general
  action: home

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/activate/:token:
  controller: user
  action: activate

/reset/:token:
  controller: user
  action: reset

/reset:
  controller: user
  action: reset

# Admin routes

/dashboard:
  controller: admin
  action: dashboard
  protected: true

/admin/orders:
  controller: admin
  action: orders

/admin/products:
  controller: admin
  action: products

/admin/users:
  controller: admin
  action: users

/admin/shop:
  controller: admin
  action: shop

/admin/pages:
  controller: admin
  action: pages

/admin/menus:
  controller: admin
  action: menus