/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forgot_password:
  controller: user
  action: forgot_password


/dashboard:
  controller: admin
  action: dashboard

/test:
  controller: general
  action: test