/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/activate/:token:
  controller: user
  action: activate

/reset/:token:
  controller: user
  action: reset

/reset:
  controller: user
  action: reset

/payment:
  controller: order
  action: payment

/order/complete:
  controller: order
  action: complete

# Admin routes

/dashboard:
  controller: admin
  action: dashboard
  protected: true

/admin/orders:
  controller: admin
  action: orders

/admin/products:
  controller: admin
  action: products

/admin/users:
  controller: adminUsers
  action: dashboard

/admin/users/edit/:id:
  controller: adminUsers
  action: edit

/admin/shop:
  controller: admin
  action: shop

/admin/pages:
  controller: admin
  action: pages

/admin/pages/create:
  controller: page
  action: create

/admin/pages/edit/:id:
  controller: page
  action: edit

/admin/pages/delete/:id:
  controller: page
  action: delete

/admin/menus:
  controller: admin
  action: menus

/admin/reviews:
  controller: admin
  action: reviews
