/:
  controller: general
  action: home

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/activate/:token:
  controller: user
  action: activate

/reset/:token:
  controller: user
  action: reset

/reset:
  controller: user
  action: reset

/admin/orders:
  controller: general
  action: home

# Admin routes

/dashboard:
  controller: admin
  action: dashboard
  protected: true
  # role: admin
