/:
  controller: general
  action: home

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/activate/:token:
  controller: user
  action: activate

# Admin routes

/dashboard:
  controller: admin
  action: dashboard
  protected: true
